import { makeStyles } from "@mui/styles";

export const useStyles=makeStyles({

    container:{
        display:'flex',
        
        background:'#fff'
    },
    box:{
             width:500,
             height:610,
             background:'#FFFFF0',
             position:'absolute',
             left:765,
             top:100,
             borderRadius:8,
             boxShadow:'0 2px 6px 0 rgba(0,0,0,.1607843137254902)'
    },
    img:{
       marginTop:50,
        width:630,
        height:350,
        paddingLeft:40,
    
      
    },
    fuel:{
       
        width:20,
        height:20,
       
        marginLeft:120,
        
    },
    seat:{
       
        width:20,
        height:20,
        
        marginLeft:170
    },
    transmission:{
        width:20,
        height:20,
        
        marginLeft:160,
        
    },
    fueltype:{
       
        width:20,
        height:20,
        marginLeft:120,
        
    },
    seater:{
        marginLeft:150,
    },

    transmissiontype:{
        width:20,
        height:20,
        marginLeft:120
    },
    subcontainer:{
      
        marginTop:20,
        background:'#c7ecee',
        padding:20,
        height:700
    },
    heading:{
   
       
        background:'blue',
        height:0,
        fontFamily:'Poppin',
        fontSize:32,
        fontWeight:800,
        paddingLeft:50
    },
    subheading:{
        height:0,
        fontFamily:'Poppin',
        fontSize:24,
        fontWeight:500,
       color:'#aaa69d',
       width:1300,
      marginTop:70,
      marginLeft:50
    },
    liability:{
        width:40,
        height:40,
        marginTop:50,
        marginLeft:50
        
    },
    limited:{
        fontSize:18,
        fontFamily:'Poppin',
        marginTop:2,
        marginLeft:50
    },
    road:{
        width:50,
        height:40,
        marginTop:50,
        marginLeft:230,
         
    },
    roadside:{
      marginTop:160,
     marginLeft:150,
     fontFamily:'Poppin',
     fontSize:18
    },
 maintain:{
       fontFamily:'Roboto',
        height:0,
        marginTop:20,
        fontSize:26,
        fontWeight:400,
        color:'#aaa69d',
        marginLeft:50
 },
 oil:{
    marginTop:50, 
    marginLeft:55,
    width:32,
    height:30
 },
 filter:{
    marginTop:50, 
    marginLeft:235,
    width:25,
    height:25
 },
 tyre:{
    marginTop:50, 
    marginLeft:235
 },
 replace:{
    marginTop:5, 
    marginLeft:55,

 },
 replacement1:{
marginLeft:55
 },
 replacement2:{
    marginLeft:180
     },
     rotation:{
        marginLeft:172
         },

 filters:{
    marginTop:50, 
    marginLeft:170
 },
 topup:{
    marginTop:50, 
    marginLeft:225
 },
 wear:{
    marginLeft:50,
    margin:30,
    fontSize:26,
    fontFamily:'Roboto',
    color:'#aaa69d',

 },
 cost:{
    fontFamily:'Poppin',
    fontSize:14,
    marginLeft:50,
    marginTop:-20
 },
 covered:{
    fontFamily:'Poppin',
    fontSize:14,
    marginLeft:50,

 },
 tyres:{
    marginLeft:55,
    marginTop:20
 },
 battery:{
    marginTop:50, 
    marginLeft:248
 },
 clutch:{
    marginTop:50, 
    marginLeft:240
 },
 tyrehead:{
    marginLeft:55
 },
 batteries:{
    marginLeft:240
 },
 clutches:{
    marginLeft:210
 },
 batteryreplace:{
    marginLeft:182
 },
 parts:{
    marginLeft:173
 },
 suspension:{
    marginLeft:230
 },
 manufacturer:{
    marginLeft:183
 },
 suspens:{
    marginLeft:237
 },
 warrenty:{
    marginLeft:230
 },
 warrent:{
    marginLeft:243
 },
 head:{
   fontFamily:'Roboto',
   fontSize:32,
   fontWeight:800,
  borderRadius:8,
   padding:15,
   background:'#f2f2f2',
   
 },
 subhead:{
   fontSize:24,
   fontWeight:600,
   fontFamily:'Poppin',
   paddingLeft:20,
   padding:10
 },
 button:{
   display:'flex',
   justifyContent:'center',
  
 },

 button1:{
   paddingLeft:20,
   paddingRight:20
 },
 
 rupee:{
   fontSize:36,
   fontFamily:'Roboto',
   fontWeight:600,
   
 },
 rupees:{
   margin:20,
   marginLeft:35
 },
 month:{
   fontFamily:'Roboto',
   fontSize:24,
   fontWeight:400
 },
 deduct:{
   fontFamily:'Roboto',
   fontSize:28,
   fontWeight:500,
   paddingLeft:15,
   color:'#00d2d3'
 },
 off:{
   fontFamily:'Roboto',
   fontSize:24,
   fontWeight:500,
   paddingLeft:10,
   color:'#00d2d3'
 },
 tax:{
   fontFamily:'Roboto',
   fontSize:14,
   fontWeight:400,
   paddingLeft:35,
   color:'#00d2d3',
   marginTop:-13
 },
 proceed:{
   margin:25,
   cursor:'pointer',
   },
 proc:{
   height:60,
   background:"linear-gradient(270deg,#1caba2 25%,#1c7fab)"
    },
    date:{
   fontSize:16,
   fontWeight:400,
   fontFamily:'Roboto',
   color:'#656565'
    },
   delivery:{
   fontSize:16,
   fontWeight:400,
   fontFamily:'Roboto',
   marginLeft:100,
   color:'##656565'
   },
   place:{
 marginLeft:50,

   },
   dates:{
      fontSize:16,
   fontWeight:600,
   fontFamily:'Poppin',
   color:'#1b1c24'
   
   },
   doorstep:{
   fontSize:16,
   fontWeight:600,
   fontFamily:'Poppin',
   marginLeft:97,
   color:'#1b1c24'
      },
  places:{
   marginTop:10
  },
  demand:{
   fontSize:13,
   fontWeight:500,
   fontFamily:'Poppin',
   color:'#d1a619',
   marginLeft:50,
   marginTop:7
  },
  tick:{
   width:20,
   height:20,
   paddingTop:15
  },
  extend:{
   fontSize:18,
   fontWeight:500,
   fontFamily:'Poppin',
   paddingLeft:10,
   color:'#1b1c24',
   position:'relative',
   top:-4
  },
  green:{
   marginLeft:50,
   marginTop:50,
   
  },
  phone:{
   width:25,
   width:25
  },
  call:{
   paddingLeft:15,
   fontSize:18,
   fontWeight:700,
   color:'#1caba2',
   fontFamily:'Poppin'
  },
  mon:{
   fontSize:16,
   fontWeight:800,
   fontFamily:'Poppin'
  }
})